server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    username: 数据库用户名
    password: 数据库密码
    url: jdbc:mysql://localhost:3306/search?characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart:
#      单个文件大小
      max-file-size: 30MB
#      单次请求大小
      max-request-size: 100MB



upload-file-parent-path: /upload/
